-- Plugin Setup
require("plugins.lz")
require("plugins.snacks")
require("plugins.treesitter")
require("plugins.gitsigns")
require("plugins.mini_setup")
require("plugins.utils")
require("plugins.ui")
require("plugins.editor")
require("plugins.motion")
require("plugins.lsp")
require("plugins.copilot-setup")
require("plugins.blink")
require("plugins.splits")
